### PR TITLE
Update ruby spec

### PR DESCRIPTION
**Pull request by ozzyaaron**

### CODE REVIEW

**Comment by ozzyaaron** [comment]
There must have been a change to Circle since the last time this project was built. Looking.

**Comment by ozzyaaron** [comment]
@dirkkelly actually could you setup deploy keys for App & this gem and then add them to Circle? 

Website and Passport use deploy keys but App and campminder-rb use your user key. It looks like your user key may have changed in the last year so Circle can't check the code out.

**Comment by dirkkelly** [comment]
Added to both

**Comment by ozzyaaron** [comment]
Thanks @dirkkelly

**Pull request merged**
